name = "LinearKernelModels"
uuid = "bc20c4a6-ae8f-539c-9805-f1e868603a0f"
author = ["Tim Holy <tim.holy@gmail.com>", "Kelly Hill Markwalter"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
